### ISSUE TITLE
YouTube videos not playing

### ISSUE THREAD

**Issue by besteman** [you-are-my-only-hope/help-site#10]
On the deployed site of the page, the YouTube videos are not showing in the fancy box

**Comment by leon-do** [comment]
The youtube video's are probably http instead of https

**Comment by realzaidiguy** [comment]
They're playing fine for me, locally. My guess is maybe a github deployment issue. I don't see any reason for them to not play. I'll try changing to https per Leon's recommendation and see if it makes a difference.

**Comment by realzaidiguy** [comment]
Switched video calls from http to https. No difference. I believe it's a github deployed sites issue. They play perfectly from local.

**Comment by realzaidiguy** [comment]
Seems to be working now. Perhaps https did the trick, and github site needed time to propagate?
